[package]
name = "rusty_fungus"
version = "0.1.0"
authors = ["Elijah Mirecki", "Joshua Wolfe"]
edition = "2018"

[dependencies]
rand = "0.7.*"
bimap = "0.4.0"
lazy_static = "1.4.0"
clap = "2.33.0"
ncurses = "5.99.0"
pad = "0.1.6"
